# Default values for jenkins-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Change Default repository

initContainerImage: "alpine:3.6"

replicaCount: 1
imagePullSecrets: ecr-registry-secret
image:
  repository: 616488335016.dkr.ecr.ap-south-1.amazonaws.com/jenkins
  tag: lts-k8s
  pullPolicy: Always
did:
  image:
    repository: docker
    tag: 18.02.0-dind
## Set the admin user
adminUser: admin
## Make sure to replace the default password
adminPassword: password
service:
  name: jenkins-k8s
  type: LoadBalancer
  ## Whitelist the IPs that can access Jenkins
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  externalPort: 8080
  internalPort: 8080
## Make sure the javaOps and resources are aligned to avoid conflicts
javaOpts: "-Xms1g -Xmx2g"
resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi
storage:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
  capacity: 50Gi
